### ISSUE TITLE
[Bug]: Does not seem to be functional

### ISSUE THREAD

**Issue by MarcusRiedner** [OpenSchooling/AccentPress#46]
### Describe the bug

Holding down a letter key for a language accent (E, O, U, etc) does not bring up a popup or activate the extension.

Fails in Gmail, Docs, Sheets, Browser based typing forms like this one. More or less the extension is non-functional everywhere.

### To Reproduce

1. Install extension
2. Press a key that has an accent in one of the active languages

### Expected Behavior

Expected is a popup to select the accented character.

### Version

v1.4.0

### What OSes are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Google Chrome

### What browser versions are you seeing the problem on?

Version 119.0.6045.124 (Official Build) (64-bit)

### Screenshots

![Screenshot_12](https://github.com/OpenSchooling/AccentPress/assets/1050954/6689ae68-3f76-4b41-a04f-e848e20fe93b)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Pandapip1** [comment]
A typo made the configuration file unreadable. This should be fixed automatically within ~1 day.
