### ISSUE TITLE
[Language]: Greek

### ISSUE THREAD

**Issue by MarcusRiedner** [OpenSchooling/AccentPress#47]
### Is your feature request related to a problem? Please describe.

Would be nifty to have greek as one of the languages - lots of accents and subscripts!

### Describe the solution you'd like

Greek as one of the languages.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Pandapip1** [comment]
Could you give me a list of accents / diacritics to add?
